// <auto-generated />
using System;
using Benefits_Backend.Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Benefits_Backend.Domain.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200710150612_first-init")]
    partial class firstinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.AppSeetingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AppSettingId")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("date");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppSettingId");

                    b.HasIndex("ChangedById");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AppSeetingHistory");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "MaxPercentWithdrawal",
                            Name = "Max Percent Withdrawal",
                            Value = "65"
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("LandlineNumber")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("StaffId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1991, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mohamed.Almokadem@vodafone.com",
                            FullName = "Mohamed AlMokadem",
                            LandlineNumber = "00226799126",
                            MobileNumber = "01015925905",
                            NationalId = "0000200230979239",
                            StaffId = "26018"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1993, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Hager@vodafone.com",
                            FullName = "Hager Ahmed",
                            LandlineNumber = "00226799126",
                            MobileNumber = "010133344555",
                            NationalId = "0000200230979239",
                            StaffId = "26782"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1992, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Mona@vodafone.com",
                            FullName = "Mona Fawzy",
                            LandlineNumber = "00224456126",
                            MobileNumber = "010133234588",
                            NationalId = "0000200230559449",
                            StaffId = "28896"
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.HistoricalMetlifeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CERT")
                        .HasColumnType("integer");

                    b.Property<float>("Contribution")
                        .HasColumnType("real");

                    b.Property<float>("Income")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<float>("NewBalance")
                        .HasColumnType("real");

                    b.Property<float>("OldBalance")
                        .HasColumnType("real");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedCERT")
                        .HasColumnType("integer");

                    b.Property<float>("UpdatedContribution")
                        .HasColumnType("real");

                    b.Property<float>("UpdatedIncome")
                        .HasColumnType("real");

                    b.Property<string>("UpdatedName")
                        .HasColumnType("text");

                    b.Property<float>("UpdatedNewBalance")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedON")
                        .HasColumnType("timestamp without time zone");

                    b.Property<float>("UpdatedOldBalance")
                        .HasColumnType("real");

                    b.Property<float>("UpdatedWithdrawals")
                        .HasColumnType("real");

                    b.Property<float>("Withdrawals")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("historicalMetlifeData");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BirthCertificate")
                        .HasColumnType("text");

                    b.Property<string>("ChildImage")
                        .HasColumnType("text");

                    b.Property<string>("ChildName")
                        .HasColumnType("text");

                    b.Property<string>("MarrigeCertificate")
                        .HasColumnType("text");

                    b.Property<string>("PersonalImage")
                        .HasColumnType("text");

                    b.Property<string>("RequestType")
                        .HasColumnType("text");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SpouseImage")
                        .HasColumnType("text");

                    b.Property<string>("SpouseName")
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("medicalCardRequests");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequestForEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("PersonalImage")
                        .HasColumnType("text");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("medicalCardRequestForEmployees");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequestForSpouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("MarrigeCertificate")
                        .HasColumnType("text");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SpouseImage")
                        .HasColumnType("text");

                    b.Property<string>("SpouseName")
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("medicalCardRequestForSpouses");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MetlifeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CERT")
                        .HasColumnType("integer");

                    b.Property<decimal>("Contribution")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("NewBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OldBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Withdrawals")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("metlifeData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CERT = 20,
                            Contribution = 85299.64m,
                            Income = 4233.757m,
                            Name = "MAHMOUD, ASHRAF",
                            NewBalance = 142326.8m,
                            OldBalance = 52793.4m,
                            Withdrawals = 0m
                        },
                        new
                        {
                            Id = 2,
                            CERT = 30,
                            Contribution = 15439.77m,
                            Income = 1277.134m,
                            Name = "Abdallah Fekry Kenawy, Abdullah Mahmoud",
                            NewBalance = 33200.45m,
                            OldBalance = 25658.55m,
                            Withdrawals = 9175m
                        },
                        new
                        {
                            Id = 3,
                            CERT = 2,
                            Contribution = 85299.64m,
                            Income = 4233.76m,
                            Name = "Mona",
                            NewBalance = 142326.80m,
                            OldBalance = 52793.40m,
                            Withdrawals = 0m
                        },
                        new
                        {
                            Id = 4,
                            CERT = 3,
                            Contribution = 89238m,
                            Income = 9438m,
                            Name = "Ziad",
                            NewBalance = 237070m,
                            OldBalance = 168140m,
                            Withdrawals = 0m
                        },
                        new
                        {
                            Id = 5,
                            CERT = 26018,
                            Contribution = 89238m,
                            Income = 9438m,
                            Name = "Mohamed AlMokadem",
                            NewBalance = 237070m,
                            OldBalance = 168140m,
                            Withdrawals = 0m
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PensionEnrollmentRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Band")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfMonthsToEnrollment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PensionEnrollmentRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Band = "S",
                            NumberOfMonthsToEnrollment = 0
                        },
                        new
                        {
                            Id = 2,
                            Band = "E",
                            NumberOfMonthsToEnrollment = 3
                        },
                        new
                        {
                            Id = 3,
                            Band = "F",
                            NumberOfMonthsToEnrollment = 3
                        },
                        new
                        {
                            Id = 4,
                            Band = "G",
                            NumberOfMonthsToEnrollment = 24
                        },
                        new
                        {
                            Id = 5,
                            Band = "H",
                            NumberOfMonthsToEnrollment = 24
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PensionEnrollmentRulesHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("BandAfter")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BandBefore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NumberOfMonthsToEnrollmentAfter")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfMonthsToEnrollmentBefore")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PensionEnrollmentRulesHistories");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PensionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ApprovedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Band")
                        .HasColumnType("text");

                    b.Property<decimal>("BeginingBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text");

                    b.Property<decimal>("CurrentAvailableBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CurrentyearContribution")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("LastRoundWithdrawal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MaxWithdrawalAmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("NumberOfMonthsToEnroll")
                        .HasColumnType("double precision");

                    b.Property<decimal>("ProratedNewContribution")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RejectedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RequestedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestedOn")
                        .HasColumnType("date");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SubBand")
                        .HasColumnType("text");

                    b.Property<double>("Tenure")
                        .HasColumnType("double precision");

                    b.Property<decimal>("VestedBalance")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VestingPercent")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("WithdrawalAmmount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("isCanceled")
                        .HasColumnType("boolean");

                    b.Property<bool>("isEligible")
                        .HasColumnType("boolean");

                    b.Property<bool>("isEnrolled")
                        .HasColumnType("boolean");

                    b.Property<bool>("isRejected")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("RequestedById");

                    b.ToTable("PensionRequests");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PhoneProgramRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("RequestById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("date");

                    b.Property<string>("RequestFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestById");

                    b.ToTable("PhoneProgramRequests");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.RoundDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("RoundDates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2020, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RoundName = "July 2020",
                            StartDate = new DateTime(2020, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.SuccessFactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Band")
                        .HasColumnType("text");

                    b.Property<string>("CostCenter")
                        .HasColumnType("text");

                    b.Property<DateTime>("HiringDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<string>("SubBand")
                        .HasColumnType("text");

                    b.Property<double>("Tenure")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("SuccessFactor");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.URLsLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("URLsLookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "PensionPolicyURL",
                            Value = ""
                        },
                        new
                        {
                            Id = 2,
                            Key = "PensionPolicyFilePath",
                            Value = ""
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.VestingRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FromYear")
                        .HasColumnType("integer");

                    b.Property<int>("ToYear")
                        .HasColumnType("integer");

                    b.Property<int>("VestingRulesPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VestingRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromYear = 2,
                            ToYear = 3,
                            VestingRulesPercentage = 50
                        },
                        new
                        {
                            Id = 2,
                            FromYear = 3,
                            ToYear = 4,
                            VestingRulesPercentage = 65
                        },
                        new
                        {
                            Id = 3,
                            FromYear = 4,
                            ToYear = 5,
                            VestingRulesPercentage = 85
                        },
                        new
                        {
                            Id = 4,
                            FromYear = 5,
                            ToYear = 0,
                            VestingRulesPercentage = 100
                        });
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.VestingRulesHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("FromYearAfter")
                        .HasColumnType("integer");

                    b.Property<int>("FromYearBefore")
                        .HasColumnType("integer");

                    b.Property<int>("ToYearAfter")
                        .HasColumnType("integer");

                    b.Property<int>("ToYearBefore")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("VestingPercentageAfter")
                        .HasColumnType("integer");

                    b.Property<int>("VestingPercentageBefore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.ToTable("VestingRulesHistories");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.AppSeetingHistory", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.AppSetting", "AppSetting")
                        .WithMany("AppSeetingHistories")
                        .HasForeignKey("AppSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", null)
                        .WithMany("AppSeetingHistories")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequest", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequestForEmployee", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.MedicalCardRequestForSpouse", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PensionEnrollmentRulesHistory", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PensionRequest", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "RequestedBy")
                        .WithMany("PensionRequests")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.PhoneProgramRequest", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "RequestBy")
                        .WithMany()
                        .HasForeignKey("RequestById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Benefits_Backend.Domain.Entities.VestingRulesHistory", b =>
                {
                    b.HasOne("Benefits_Backend.Domain.Entities.Employee", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
